services:
  app:
    container_name: swarmcloud
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi:application
    restart: always
    build:
      context: .
    networks:
      - db_network
      - web_network
    volumes:
      - ./:/app
      - /var/run/tailscale:/var/run/tailscale:ro
      - /usr/bin/tailscale:/usr/bin/tailscale:ro
    depends_on:
      - postgres
      - redis
      - docker-proxy
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DOCKER_HOST=tcp://docker-proxy:2375

  celery_worker:
    container_name: celery_worker
    command: celery -A core worker --loglevel=info --concurrency=2
    restart: always
    build:
      context: .
    networks:
      - db_network
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
      - docker-proxy
    env_file:
      - .env
    environment:
      - DOCKER_HOST=tcp://docker-proxy:2375

  docker-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker-proxy
    restart: always
    networks:
      - db_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - NETWORKS=1
      - VOLUMES=1
      - BUILD=1
      - VERSION=1
      - AUTH=1
      - SECRETS=0
      - POST=1
      - EXEC=1
    # Only allow internal access from the project containers
    expose:
      - "2375"

  redis:
    image: redis:7.0.12
    container_name: redis
    command: ["redis-server", "--port", "6379", "--requirepass", "${REDIS_PASSWORD}", "--slave-read-only", "no"]
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - db_network


  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    networks:
      - db_network

  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - minio_data:/data
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    env_file:
      - .env
    command: server /data --console-address ":9001"
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
