version: "3.8"
services:
  app:
    container_name: mediswarmcloud
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    build:
      context: .
    networks:
      - db_network
      - web_network
      - flare_network
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/tailscale:/var/run/tailscale:ro
      - /usr/bin/tailscale:/usr/bin/tailscale:ro
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env

  celery_worker:
    container_name: celery_worker
    command: celery -A core worker --loglevel=info --concurrency=2
    restart: always
    build:
      context: .
    networks:
      - db_network
      - flare_network
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - C_FORCE_ROOT=1  # Allow Celery to run as root in Docker

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - app

  redis:
    image: redis:7.0.12
    container_name: redis
    command: ["redis-server", "--port", "6379", "--slave-read-only", "no"]
    restart: always
    ports:
      - 6379:6379
    networks:
      - db_network

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - db_network

  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    command: server /data --console-address ":9001"
    networks:
      - db_network
  
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - db_network
    depends_on:
      - postgres

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
  flare_network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
