# Generated by Django 4.2.9 on 2025-11-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STARTING', 'Starting'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=20),
        ),
    ]
