# Generated by Django 4.2.9 on 2025-12-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_trainingjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingjob',
            name='flare_job_id',
            field=models.CharField(blank=True, help_text='The unique job ID assigned by NVIDIA FLARE.', max_length=255, null=True),
        ),
    ]
