# Generated by Django 6.0 on 2026-01-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_trainingjob_flare_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STARTING', 'Starting'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
