# Generated by Django 6.0 on 2026-01-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0002_backupconfiguration_include_s3_storage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backupconfiguration",
            name="s3_access_key_id",
            field=models.CharField(
                blank=True,
                help_text="Custom S3 Access Key ID.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="backupconfiguration",
            name="s3_endpoint_url",
            field=models.CharField(
                blank=True,
                help_text="Custom S3 Endpoint (e.g., https://s3.amazonaws.com).",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="backupconfiguration",
            name="s3_region_name",
            field=models.CharField(
                blank=True, help_text="Custom S3 Region.", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="backupconfiguration",
            name="s3_secret_access_key",
            field=models.CharField(
                blank=True,
                help_text="Custom S3 Secret Access Key.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="backupconfiguration",
            name="s3_bucket",
            field=models.CharField(
                blank=True, help_text="S3 Bucket name.", max_length=255
            ),
        ),
    ]
