# Generated by Django 6.0 on 2026-03-18 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_backupconfiguration_s3_access_key_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupconfiguration',
            name='include_databases',
            field=models.BooleanField(default=True, help_text='Whether to include databases in the backup.'),
        ),
        migrations.AlterField(
            model_name='backupconfiguration',
            name='include_media',
            field=models.BooleanField(default=True, help_text='Whether to include media files in the backup.'),
        ),
        migrations.AlterField(
            model_name='backupconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this configuration is currently active.'),
        ),
        migrations.AlterField(
            model_name='backupconfiguration',
            name='name',
            field=models.CharField(default='Default Configuration', help_text='Name of the backup configuration.', max_length=255),
        ),
        migrations.AlterField(
            model_name='backupconfiguration',
            name='retention_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days to keep backup logs and files.'),
        ),
        migrations.AlterField(
            model_name='backupconfiguration',
            name='storage_backend',
            field=models.CharField(choices=[('local', 'Local Filesystem'), ('s3', 'S3 / MinIO Storage')], default='s3', help_text='Target storage backend for backups.', max_length=20),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='config',
            field=models.ForeignKey(help_text='The configuration used for this backup.', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='backup.backupconfiguration'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if the backup failed.'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='Size of the backup file in bytes.', null=True),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='filename',
            field=models.CharField(blank=True, help_text='Name of the generated backup file.', max_length=255),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='When the backup operation finished.', null=True),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='has_media',
            field=models.BooleanField(default=False, help_text='Whether media files were included.'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='has_s3_storage',
            field=models.BooleanField(default=False, help_text='Whether S3 storage was included.'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='included_databases',
            field=models.JSONField(default=list, help_text='List of database aliases included in the backup.'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the backup operation started.'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('restoring', 'Restoring')], default='pending', help_text='Current status of the backup operation.', max_length=20),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='storage_location',
            field=models.CharField(blank=True, help_text='Path or URL to the stored backup file.', max_length=1024),
        ),
    ]
