# Generated by Django 5.1.7 on 2025-10-04 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0004_project_data_visualization_script'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwarmNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('INITIALIZING', 'Initializing'), ('PROVISIONED', 'Provisioned'), ('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], default='INITIALIZING', max_length=20)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swarm_networks', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='SwarmParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SERVER', 'Server'), ('CLIENT', 'Client')], max_length=10)),
                ('participant_id', models.CharField(help_text="Unique identifier used by FLARE (e.g., 'server', 'client-1')", max_length=100)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='network.swarmnetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swarm_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('network', 'participant_id')},
            },
        ),
    ]
