# Generated by Django 6.0 on 2026-03-18 08:00

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_add_admin_startup_dir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swarmnetwork',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='swarmnetwork',
            name='creation_method',
            field=models.CharField(choices=[('CREATED', 'Created (locally provisioned)'), ('IMPORTED', 'Imported (from existing config)'), ('LOCAL_TEST', 'Local Test')], default='CREATED', help_text='How this network configuration was initialized.', max_length=20),
        ),
        migrations.AddField(
            model_name='swarmnetwork',
            name='gossip_token',
            field=common.fields.EncryptedCharField(blank=True, help_text='Shared secret for authenticating gossip status shouts.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='swarmparticipant',
            name='gossip_token',
            field=common.fields.EncryptedCharField(blank=True, help_text='Participant-scoped secret for authenticated gossip and internal APIs.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='swarmparticipant',
            name='ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='swarmparticipant',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swarmparticipant',
            name='org',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='swarmparticipant',
            name='status',
            field=models.CharField(default='OFFLINE', max_length=50),
        ),
    ]
