# Generated by Django 4.2.9 on 2025-10-06 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0002_swarmnetwork_author_swarmnetwork_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCurrentNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_users', to='network.swarmnetwork')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_network_relation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'network')},
            },
        ),
    ]
