# Generated by Django 4.2.9 on 2025-10-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_usercurrentnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swarmnetwork',
            name='status',
            field=models.CharField(choices=[('INITIALIZING', 'Initializing'), ('PROVISIONED', 'Provisioned'), ('STARTING', 'Starting'), ('RUNNING', 'Running'), ('STOPPING', 'Stopping'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], default='INITIALIZING', max_length=20),
        ),
    ]
