# Generated by Django 6.0 on 2026-01-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_swarmnetwork_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swarmnetwork',
            name='status',
            field=models.CharField(choices=[('INITIALIZING', 'Initializing'), ('PROVISIONED', 'Provisioned'), ('STARTING', 'Starting'), ('RUNNING', 'Running'), ('STOPPING', 'Stopping'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], db_index=True, default='INITIALIZING', max_length=20),
        ),
    ]
