# Generated by Django 6.0 on 2026-01-03 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_swarmnetwork_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='swarmparticipant',
            index=models.Index(fields=['user', 'network'], name='network_swa_user_id_169a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='swarmparticipant',
            index=models.Index(fields=['network', 'role'], name='network_swa_network_3be9c1_idx'),
        ),
    ]
