# Generated by Django 4.2.9 on 2025-05-22 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_city_profile_country_profile_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
