# Generated by Django 4.2.9 on 2025-05-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
