# Generated by Django 6.0 on 2026-01-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepted_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='accepted_policy_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='accepted_terms_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
