# Generated by Django 6.0 on 2026-01-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_accepted_policy_profile_accepted_policy_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cookie_consent',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cookie_consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
