# Generated by Django 6.0 on 2026-01-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_cookie_consent_profile_cookie_consent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emergency_access_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_access_justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_emergency_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='restriction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
