# Generated by Django 6.0 on 2026-01-03 08:54

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_emergency_access_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_access_justification',
            field=apps.core.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
