# Generated by Django 4.2.9 on 2025-05-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='FileInfo',
        ),
    ]
