# Generated by Django 4.2.9 on 2025-05-23 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('training_code', models.FileField(blank=True, null=True, upload_to='training_code/')),
                ('data_validation_script', models.FileField(blank=True, null=True, upload_to='data_validation/')),
                ('results_visualization_script', models.FileField(blank=True, null=True, upload_to='results_visualization/')),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
    ]
