# Generated by Django 6.0 on 2026-03-18 08:01

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='secret',
            field=common.fields.EncryptedCharField(blank=True, help_text='Project-specific secret for container authentication.', max_length=128, null=True, unique=True),
        ),
    ]
