# Generated by Django 4.2.9 on 2025-05-23 08:57

import apps.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_members_alter_project_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data_validation_script',
            field=models.FileField(blank=True, null=True, upload_to=apps.project.models.data_validation_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='results_visualization_script',
            field=models.FileField(blank=True, null=True, upload_to=apps.project.models.results_visualization_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='training_code',
            field=models.FileField(blank=True, null=True, upload_to=apps.project.models.training_code_path),
        ),
    ]
