# Generated by Django 4.2.9 on 2025-05-29 12:03

import apps.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_data_validation_script_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_visualization_script',
            field=models.FileField(blank=True, null=True, upload_to=apps.project.models.data_visualization_path),
        ),
    ]
