# Generated by Django 4.2.9 on 2025-10-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished')], default='IN_PROGRESS', max_length=20),
        ),
    ]
