# Generated by Django 4.2.9 on 2025-10-20 18:03

import apps.project.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='requirements_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.project.utils.training_code_path),
        ),
    ]
