# Generated by Django 4.2.9 on 2025-10-20 18:12

import apps.project.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_requirements_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='requirements_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.project.utils.requirements_path),
        ),
    ]
