# Generated by Django 4.2.9 on 2025-12-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_project_requirements_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('ARCHIVED', 'Archived')], default='IN_PROGRESS', max_length=20),
        ),
    ]
