# Generated by Django 6.0 on 2026-01-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('ARCHIVED', 'Archived')], db_index=True, default='IN_PROGRESS', max_length=20),
        ),
    ]
