# Generated by Django 6.0 on 2026-01-03 14:48

import apps.project.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_project_creation_date_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data_validation_script',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=apps.project.utils.data_validation_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='data_visualization_script',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=apps.project.utils.data_visualization_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=apps.project.utils.requirements_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='results_visualization_script',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=apps.project.utils.results_visualization_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='training_code',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=apps.project.utils.training_code_path),
        ),
    ]
