"""
NVIDIA FLARE Adapter for SwarmCloud.
This module provides a simplified interface for training scripts to interact
with the NVFlare system and the project's S3 data storage.
"""

import json
import os
import shutil
import ssl
import tempfile
import urllib.request
from typing import Iterator
from urllib.parse import urlparse

import boto3
from botocore.config import Config
import numpy as np
import nvflare.client as flare
from dotenv import load_dotenv

# Load environment variables from a local .env file if it exists.
load_dotenv()


class FlareDataFileSystem:
    """
    A self-contained virtual filesystem for NVFlare jobs.

    Provides a file-like interface to data stored in an S3-compatible service (MinIO).
    It works by creating a temporary local directory and downloading files using
    presigned URLs provided in a data manifest, allowing training scripts to use
    standard file I/O operations without needing S3 credentials.
    """

    def __init__(self, project_uuid: str):
        """
        Initialize the filesystem with the project's unique identifier.
        """
        self.project_uuid = (
            os.getenv("SWARMCLOUD_PROJECT_ID", "").strip() or project_uuid
        )

        # Create a temporary directory on the local machine to store downloaded
        # files.
        self.temp_dir = tempfile.mkdtemp(prefix=f"flare_{project_uuid}_")

        # Track which files have already been downloaded to avoid redundant
        # network calls.
        self._downloaded_files = {}

        self.use_local_data = (
            os.getenv("SWARMCLOUD_USE_LOCAL_DATA", "1").strip().lower()
            in {"1", "true", "yes", "on"}
        )

        self.bucket = os.getenv("AWS_STORAGE_BUCKET_NAME", "").strip()
        self.s3_client = None
        self.local_s3_endpoint = (
            os.getenv("SWARMCLOUD_LOCAL_S3_ENDPOINT", "").strip()
            or os.getenv("AWS_S3_ENDPOINT_URL", "").strip()
            or ""
        )
        self.local_s3_region = os.getenv("AWS_S3_REGION_NAME", "").strip()
        if self.use_local_data and self.bucket:
            try:
                self.s3_client = self._build_s3_client(
                    endpoint_url=self.local_s3_endpoint or None,
                    region_name=self.local_s3_region or None,
                    addressing_style="path",
                )
                print(
                    "FlareDataFileSystem: Local S3 client initialized "
                    f"(endpoint={self.local_s3_endpoint or None}, bucket={self.bucket}, project={self.project_uuid})."
                )
            except Exception as e:
                print(
                    f"FlareDataFileSystem: WARNING - Failed to initialize local S3 client: {e}"
                )

        # Load the data manifest containing presigned URLs.
        # This file is generated by the server and bundled with the job.
        self.manifest = {}

        # Setup SSL context for internal S3 downloads
        # We allow self-signed certificates because the internal MinIO uses them
        self.ssl_context = ssl.create_default_context()
        self.ssl_context.check_hostname = False
        self.ssl_context.verify_mode = ssl.CERT_NONE

        # Try multiple locations for data_manifest.json to be robust across different NVFlare executors
        manifest_locations = [
            os.path.join(os.getcwd(), "data_manifest.json"),
            os.path.join(os.path.dirname(__file__), "data_manifest.json"),
            os.path.join(os.getcwd(), "custom", "data_manifest.json"),
        ]

        manifest_path = None
        for loc in manifest_locations:
            if os.path.exists(loc):
                manifest_path = loc
                break

        if manifest_path:
            try:
                with open(manifest_path) as f:
                    self.manifest = json.load(f)
                print(
                    f"FlareDataFileSystem: Loaded manifest from {manifest_path} with {len(self.manifest)} files."
                )
            except Exception as e:
                print(
                    f"FlareDataFileSystem: ERROR - Failed to load manifest from {manifest_path}: {e}"
                )
        else:
            print(
                "FlareDataFileSystem: WARNING - data_manifest.json not found in search paths."
            )

        print(f"FlareDataFileSystem: Initialized. Temp dir: {self.temp_dir}")

    def _build_s3_client(
        self,
        endpoint_url: str | None,
        region_name: str | None,
        addressing_style: str,
    ):
        return boto3.client(
            "s3",
            aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
            aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
            region_name=region_name,
            endpoint_url=endpoint_url,
            config=Config(
                signature_version="s3v4",
                s3={"addressing_style": addressing_style},
            ),
        )

    def _candidate_object_keys(self, rel_path: str) -> list[str]:
        keys = [
            f"{self.project_uuid}/data/{rel_path}",
            f"{self.project_uuid}/{rel_path}",
            rel_path,
        ]
        seen = set()
        deduped = []
        for key in keys:
            normalized = key.lstrip("/")
            if normalized and normalized not in seen:
                seen.add(normalized)
                deduped.append(normalized)
        return deduped

    def _iter_local_s3_clients(self) -> Iterator[tuple[str, object]]:
        if self.s3_client is not None:
            yield ("primary", self.s3_client)

        endpoint_candidates = []
        configured_endpoint = (
            self.local_s3_endpoint
            or os.getenv("AWS_S3_ENDPOINT_URL", "").strip()
        )
        if configured_endpoint:
            endpoint_candidates.append(configured_endpoint)

            if "://" in configured_endpoint:
                try:
                    parsed = urlparse(configured_endpoint)
                    if parsed.scheme and parsed.netloc and parsed.hostname:
                        localhost_netloc = "127.0.0.1"
                        if parsed.port:
                            localhost_netloc = f"{localhost_netloc}:{parsed.port}"
                        localhost_endpoint = parsed._replace(
                            netloc=localhost_netloc
                        ).geturl()
                        if localhost_endpoint not in endpoint_candidates:
                            endpoint_candidates.append(localhost_endpoint)
                except Exception:
                    pass

        for endpoint in [
            "http://127.0.0.1:9000",
            "https://127.0.0.1:9000",
            "http://localhost:9000",
            "https://localhost:9000",
        ]:
            endpoint = (endpoint or "").strip()
            if endpoint and endpoint not in endpoint_candidates:
                endpoint_candidates.append(endpoint)

        region_candidates = []
        for region in [self.local_s3_region, "us-east-1", None]:
            value = region.strip() if isinstance(region, str) else None
            if value == "":
                value = None
            if value not in region_candidates:
                region_candidates.append(value)

        for endpoint in endpoint_candidates:
            for region in region_candidates:
                for style in ("path", "virtual"):
                    label = f"endpoint={endpoint}, region={region}, style={style}"
                    try:
                        yield (
                            label,
                            self._build_s3_client(
                                endpoint_url=endpoint,
                                region_name=region,
                                addressing_style=style,
                            ),
                        )
                    except Exception:
                        continue

    def _download_from_local_s3(self, rel_path: str, local_path: str) -> bool:
        if not (self.bucket and self.use_local_data):
            return False

        attempted_errors = []
        key_candidates = self._candidate_object_keys(rel_path)
        for client_label, client in self._iter_local_s3_clients():
            for object_key in key_candidates:
                try:
                    response = client.get_object(
                        Bucket=self.bucket,
                        Key=object_key,
                    )
                    with open(local_path, "wb") as out_file:
                        shutil.copyfileobj(response["Body"], out_file)
                    if object_key != key_candidates[0]:
                        print(
                            "FlareDataFileSystem: Local S3 fetch succeeded with fallback "
                            f"key '{object_key}' ({client_label})."
                        )
                    return True
                except Exception as e:
                    attempted_errors.append(
                        f"{client_label} key={object_key} err={e}"
                    )

        if attempted_errors:
            print(
                "FlareDataFileSystem: WARNING - Local S3 fetch attempts failed: "
                + " | ".join(attempted_errors[:4])
            )
        return False

    def __enter__(self):
        """Support for 'with' statement."""
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Ensure cleanup of temporary files when the context is closed."""
        if exc_type:
            print(
                f"FlareDataFileSystem: Exiting context with error: {exc_val}"
            )
        self.cleanup()

    def cleanup(self):
        """Deletes the temporary directory and all its contents."""
        print(f"FlareDataFileSystem: Cleaning up directory {self.temp_dir}")
        if os.path.exists(self.temp_dir):
            shutil.rmtree(self.temp_dir)

    def _download_all_from_manifest(self):
        """
        Downloads all files listed in the manifest into the
        local temporary directory using presigned URLs.
        """
        if not self.manifest:
            print(
                "FlareDataFileSystem: ERROR - No manifest loaded, cannot download data."
            )
            return

        file_count = 0
        for rel_path, url in self.manifest.items():
            local_path = os.path.join(self.temp_dir, rel_path)

            # Only download if we haven't seen this path yet.
            if local_path not in self._downloaded_files.values():
                os.makedirs(os.path.dirname(local_path), exist_ok=True)

                try:
                    print(f"FlareDataFileSystem: Downloading {rel_path}...")

                    downloaded = False

                    if self.bucket and self.use_local_data:
                        downloaded = self._download_from_local_s3(
                            rel_path=rel_path,
                            local_path=local_path,
                        )
                        if not downloaded:
                            print(
                                "FlareDataFileSystem: WARNING - Local S3 fetch failed "
                                f"for {rel_path}. Falling back to URL."
                            )

                    if not downloaded:
                        # Validate URL scheme to prevent file:// or other unexpected schemes (Bandit B310)
                        if not url.startswith(("http://", "https://")):
                            print(
                                f"FlareDataFileSystem: ERROR - Unsafe URL scheme in manifest: {url}"
                            )
                            continue

                        # Create an opener that uses our SSL context (ignoring cert verification for internal network)
                        opener = urllib.request.build_opener(
                            urllib.request.HTTPSHandler(context=self.ssl_context)
                        )
                        with (
                            opener.open(url) as response,
                            open(local_path, "wb") as out_file,
                        ):
                            shutil.copyfileobj(response, out_file)

                    self._downloaded_files[rel_path] = local_path
                    file_count += 1
                except Exception as e:
                    print(
                        f"FlareDataFileSystem: ERROR - Failed to download {rel_path}: {e}"
                    )

        if file_count == 0:
            print("FlareDataFileSystem: WARNING - No files were downloaded.")
        else:
            print(
                f"FlareDataFileSystem: Successfully downloaded {file_count} files."
            )

    def get_data_path(self) -> str:
        """
        Ensures all project data is synced locally and returns the root path.
        User scripts use this path to locate their CSVs, images, etc.
        """
        self._download_all_from_manifest()
        return self.temp_dir


# =================================================================================
# Public Adapter Functions
# =================================================================================


def init_flare():
    """
    Initializes the NVFlare client.
    Must be called at the very beginning of training.py.
    """
    flare.init()
    print("flare_adapter: NVIDIA FLARE client initialized.")


def get_data_filesystem(project_id: str) -> FlareDataFileSystem:
    """
    Factory function to create a FlareDataFileSystem instance.
    """
    return FlareDataFileSystem(project_uuid=project_id)


def receive_model():
    """
    Receives the latest global model (aggregated weights) from the server.

    Returns:
        flare.FLModel: The received model object, or None if training is done.
    """
    print("flare_adapter: Receiving global model from server...")
    try:
        input_model = flare.receive()
        if input_model:
            print(
                "flare_adapter: Global model received for "
                f"round {input_model.current_round}."
            )
            return input_model

        print("flare_adapter: No model received. Training is likely complete.")
        return None
    except Exception as e:
        print(f"flare_adapter: Exception during model reception: {e}")
        return None


def send_model(params, metrics: dict = None):
    """
    Sends the locally updated model weights and optional metrics back to the server.

    Args:
        params (dict): Model weights as a dictionary of numpy arrays.
        metrics (dict, optional): Accuracy, loss, or other performance indicators.
    """
    print("flare_adapter: Sending updated model to server...")

    if params is None:
        raise ValueError(
            "flare_adapter.send_model received params=None. "
            "Training must send model weights (e.g. model.state_dict() for PyTorch, model.get_weights() for Keras)."
        )

    # Accept common model-weight structures and normalize to dict[str, value].
    if isinstance(params, (list, tuple)):
        params = {str(i): v for i, v in enumerate(params)}
    elif not isinstance(params, dict):
        raise TypeError(
            f"flare_adapter.send_model expects dict/list/tuple for params, got {type(params)}"
        )

    if len(params) == 0:
        raise ValueError(
            "flare_adapter.send_model received empty params. "
            "No model weights were produced by training."
        )

    # Ensure all data types (like PyTorch tensors) are converted to numpy for transport.
    params = _ensure_transportable(params)

    if len(params) == 0:
        raise ValueError(
            "flare_adapter.send_model converted params are empty; cannot submit update without weights."
        )

    output_model = flare.FLModel(
        params=params,
        metrics=metrics if metrics is not None else {},
    )
    flare.send(output_model)
    print("flare_adapter: Model successfully sent to server.")


# =================================================================================
# Helper functions for framework-specific conversions
# =================================================================================


def get_weights_list(params: dict):
    """
    Converts a dictionary of parameters back to a sorted list of numpy arrays.
    Required for Keras/TensorFlow's model.set_weights() method.
    """
    try:
        # Sort by key (assuming keys are string indices "0", "1", "2"...)
        sorted_keys = sorted(params.keys(), key=lambda x: int(x))
        return [np.array(params[k]) for k in sorted_keys]
    except (ValueError, AttributeError):
        # Fallback to simple sorted values if keys aren't numeric.
        return [np.array(v) for k, v in sorted(params.items())]


def get_pytorch_state_dict(params: dict):
    """
    Converts a dictionary of numpy arrays to PyTorch tensors.
    Required for PyTorch's model.load_state_dict() method.
    """
    import torch

    return {k: torch.as_tensor(v) for k, v in params.items()}


def _ensure_transportable(params: dict):
    """
    Utility to ensure all parameters are converted to numpy arrays
    before being sent over the network by NVFlare.
    """
    converted = {}
    for k, v in params.items():
        # Keep torch tensors as tensors for PTInProcessClientAPIExecutor,
        # which expects tensor params and handles conversion internally.
        if hasattr(v, "detach") and hasattr(v, "cpu"):
            converted[k] = v.detach().cpu()
        elif hasattr(v, "numpy"):  # Handle TensorFlow/Keras tensors
            converted[k] = v.numpy()
        else:
            converted[k] = np.array(v)
    return converted
