"""
NVIDIA FLARE Adapter for SwarmCloud.
This module provides a simplified interface for training scripts to interact
with the NVFlare system and the project's S3 data storage.
"""

import json
import os
import shutil
import tempfile
import urllib.request

import numpy as np
import nvflare.client as flare
from dotenv import load_dotenv

# Load environment variables from a local .env file if it exists.
load_dotenv()


class FlareDataFileSystem:
    """
    A self-contained virtual filesystem for NVFlare jobs.

    Provides a file-like interface to data stored in an S3-compatible service (MinIO).
    It works by creating a temporary local directory and downloading files using
    presigned URLs provided in a data manifest, allowing training scripts to use
    standard file I/O operations without needing S3 credentials.
    """

    def __init__(self, project_uuid: str):
        """
        Initialize the filesystem with the project's unique identifier.
        """
        self.project_uuid = project_uuid
        # Standard prefix where data is stored in the S3 bucket.
        self.root_prefix = f"{project_uuid}/data/"

        # Create a temporary directory on the local machine to store downloaded
        # files.
        self.temp_dir = tempfile.mkdtemp(prefix=f"flare_{project_uuid}_")

        # Track which files have already been downloaded to avoid redundant
        # network calls.
        self._downloaded_files = {}

        # Load the data manifest containing presigned URLs.
        # This file is generated by the server and bundled with the job.
        self.manifest = {}
        
        # Try multiple locations for data_manifest.json to be robust across different NVFlare executors
        manifest_locations = [
            os.path.join(os.getcwd(), 'data_manifest.json'),
            os.path.join(os.path.dirname(__file__), 'data_manifest.json'),
            os.path.join(os.getcwd(), 'custom', 'data_manifest.json'),
        ]
        
        manifest_path = None
        for loc in manifest_locations:
            if os.path.exists(loc):
                manifest_path = loc
                break

        if manifest_path:
            try:
                with open(manifest_path, 'r') as f:
                    self.manifest = json.load(f)
                print(f"FlareDataFileSystem: Loaded manifest from {manifest_path} with {len(self.manifest)} files.")
            except Exception as e:
                print(f"FlareDataFileSystem: ERROR - Failed to load manifest from {manifest_path}: {e}")
        else:
            print("FlareDataFileSystem: WARNING - data_manifest.json not found in search paths.")

        print(f"FlareDataFileSystem: Initialized. Temp dir: {self.temp_dir}")

    def __enter__(self):
        """Support for 'with' statement."""
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Ensure cleanup of temporary files when the context is closed."""
        if exc_type:
            print(
                f"FlareDataFileSystem: Exiting context with error: {exc_val}")
        self.cleanup()

    def cleanup(self):
        """Deletes the temporary directory and all its contents."""
        print(f"FlareDataFileSystem: Cleaning up directory {self.temp_dir}")
        if os.path.exists(self.temp_dir):
            shutil.rmtree(self.temp_dir)

    def _download_all_from_manifest(self):
        """
        Downloads all files listed in the manifest into the
        local temporary directory using presigned URLs.
        """
        if not self.manifest:
            print("FlareDataFileSystem: ERROR - No manifest loaded, cannot download data.")
            return

        file_count = 0
        for rel_path, url in self.manifest.items():
            local_path = os.path.join(self.temp_dir, rel_path)

            # Only download if we haven't seen this path yet.
            if local_path not in self._downloaded_files.values():
                os.makedirs(os.path.dirname(local_path), exist_ok=True)
                
                # SECURITY: Use the presigned URL provided in the manifest.
                # No S3 credentials needed here.
                try:
                    print(f"FlareDataFileSystem: Downloading {rel_path}...")
                    urllib.request.urlretrieve(url, local_path)
                    self._downloaded_files[rel_path] = local_path
                    file_count += 1
                except Exception as e:
                    print(f"FlareDataFileSystem: ERROR - Failed to download {rel_path}: {e}")

        if file_count == 0:
            print("FlareDataFileSystem: WARNING - No files were downloaded.")
        else:
            print(f"FlareDataFileSystem: Successfully downloaded {file_count} files.")

    def get_data_path(self) -> str:
        """
        Ensures all project data is synced locally and returns the root path.
        User scripts use this path to locate their CSVs, images, etc.
        """
        self._download_all_from_manifest()
        return self.temp_dir


# =================================================================================
# Public Adapter Functions
# =================================================================================

def init_flare():
    """
    Initializes the NVFlare client.
    Must be called at the very beginning of training.py.
    """
    flare.init()
    print("flare_adapter: NVIDIA FLARE client initialized.")


def get_data_filesystem(project_id: str) -> FlareDataFileSystem:
    """
    Factory function to create a FlareDataFileSystem instance.
    """
    return FlareDataFileSystem(project_uuid=project_id)


def receive_model():
    """
    Receives the latest global model (aggregated weights) from the server.

    Returns:
        flare.FLModel: The received model object, or None if training is done.
    """
    print("flare_adapter: Receiving global model from server...")
    try:
        input_model = flare.receive()
        if input_model:
            print(
                "flare_adapter: Global model received for "
                f"round {input_model.current_round}."
            )
            return input_model

        print("flare_adapter: No model received. Training is likely complete.")
        return None
    except Exception as e:
        print(f"flare_adapter: Exception during model reception: {e}")
        return None


def send_model(params: dict, metrics: dict = None):
    """
    Sends the locally updated model weights and optional metrics back to the server.

    Args:
        params (dict): Model weights as a dictionary of numpy arrays.
        metrics (dict, optional): Accuracy, loss, or other performance indicators.
    """
    print("flare_adapter: Sending updated model to server...")

    # Ensure all data types (like PyTorch tensors) are converted to numpy for
    # transport.
    params = _ensure_transportable(params)

    output_model = flare.FLModel(
        params=params,
        metrics=metrics if metrics is not None else {},
    )
    flare.send(output_model)
    print("flare_adapter: Model successfully sent to server.")


# =================================================================================
# Helper functions for framework-specific conversions
# =================================================================================

def get_weights_list(params: dict):
    """
    Converts a dictionary of parameters back to a sorted list of numpy arrays.
    Required for Keras/TensorFlow's model.set_weights() method.
    """
    try:
        # Sort by key (assuming keys are string indices "0", "1", "2"...)
        sorted_keys = sorted(params.keys(), key=lambda x: int(x))
        return [np.array(params[k]) for k in sorted_keys]
    except (ValueError, AttributeError):
        # Fallback to simple sorted values if keys aren't numeric.
        return [np.array(v) for k, v in sorted(params.items())]


def get_pytorch_state_dict(params: dict):
    """
    Converts a dictionary of numpy arrays to PyTorch tensors.
    Required for PyTorch's model.load_state_dict() method.
    """
    import torch
    return {k: torch.as_tensor(v) for k, v in params.items()}


def _ensure_transportable(params: dict):
    """
    Utility to ensure all parameters are converted to numpy arrays
    before being sent over the network by NVFlare.
    """
    converted = {}
    for k, v in params.items():
        if hasattr(v, "cpu"):  # Handle PyTorch tensors
            converted[k] = v.cpu().numpy()
        elif hasattr(v, "numpy"):  # Handle TensorFlow/Keras tensors
            converted[k] = v.numpy()
        else:
            # Assume it's already numpy-compatible or needs simple wrapping.
            converted[k] = np.array(v)
    return converted