# Generated by Django 4.2.9 on 2025-05-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_file_folder_delete_document_file_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='parent',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
