# Generated by Django 4.2.9 on 2025-05-29 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_data_visualization_script'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualization_runs', to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisualizationPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('plot_number', models.IntegerField()),
                ('image_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visualization_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='data.visualizationrun')),
            ],
            options={
                'ordering': ['plot_number'],
                'unique_together': {('visualization_run', 'plot_number')},
            },
        ),
    ]
