# Generated by Django 4.2.9 on 2025-12-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_visualizationrun_visualizationplot'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationplot',
            name='svg_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
