# Generated by Django 6.0 on 2026-01-03 10:32

import apps.data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_validationcheck_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizationplot',
            name='image_data',
            field=models.ImageField(upload_to=apps.data.models.visualization_plot_path),
        ),
        migrations.AlterField(
            model_name='visualizationplot',
            name='svg_data',
            field=models.FileField(blank=True, null=True, upload_to=apps.data.models.visualization_plot_path),
        ),
    ]
