# Generated by Django 6.0 on 2026-01-03 14:47

import apps.data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_visualizationplot_image_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizationplot',
            name='image_data',
            field=models.ImageField(max_length=512, upload_to=apps.data.models.visualization_plot_path),
        ),
        migrations.AlterField(
            model_name='visualizationplot',
            name='svg_data',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=apps.data.models.visualization_plot_path),
        ),
    ]
