# Generated by Django 4.2.9 on 2025-05-30 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0004_project_data_visualization_script'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('project', 'Project'), ('data', 'Data'), ('network', 'Network'), ('training', 'Training'), ('results', 'Results')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('log_file_path', models.CharField(blank=True, max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('project', 'Project'), ('data', 'Data'), ('network', 'Network'), ('training', 'Training'), ('results', 'Results')], max_length=20)),
                ('session_id', models.UUIDField(default=uuid.uuid4)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'project', 'category'], name='logs_logent_user_id_b515d6_idx'), models.Index(fields=['timestamp'], name='logs_logent_timesta_1e81d2_idx'), models.Index(fields=['session_id'], name='logs_logent_session_100d9a_idx')],
            },
        ),
    ]
