# Generated by Django 4.2.9 on 2025-05-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='logsession',
            name='log_file_path',
        ),
    ]
