# Generated by Django 4.2.9 on 2025-05-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_remove_logentry_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsession',
            name='project',
        ),
        migrations.RemoveField(
            model_name='logsession',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='logentry',
            name='logs_logent_session_100d9a_idx',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='session_id',
        ),
        migrations.DeleteModel(
            name='LogSession',
        ),
    ]
