# Generated by Django 5.1.7 on 2025-10-04 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_remove_logsession_project_remove_logsession_user_and_more'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='source',
            field=models.CharField(blank=True, help_text='e.g., overseer, fl-client-1, celery', max_length=50),
        ),
        migrations.AddField(
            model_name='logentry',
            name='swarm_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='network.swarmnetwork'),
        ),
    ]
