# Generated by Django 6.0 on 2026-01-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_logsigningkey_alter_logentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
