# Generated by Django 6.0 on 2026-01-03 08:54

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_logentry_ip_address_logentry_object_id_logentry_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='message',
            field=apps.core.fields.EncryptedTextField(),
        ),
    ]
