# Generated by Django 6.0 on 2026-01-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_alter_logentry_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='source',
            field=models.CharField(default='web', max_length=100),
        ),
    ]
