# Generated by Django 6.0 on 2026-03-18 08:01

import common.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('project', '0002_project_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=common.fields.EncryptedTextField(help_text='The actual content of the message (encrypted).'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='Tracks if the recipient has seen the message.'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(help_text='The user who receives the message.', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(help_text='The user who sent the message.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=common.fields.EncryptedCharField(help_text='The subject line of the message (encrypted).', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectboardaccess',
            name='project',
            field=models.ForeignKey(help_text='The project board that was accessed.', on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='project.project'),
        ),
        migrations.AlterField(
            model_name='projectboardaccess',
            name='user',
            field=models.ForeignKey(help_text='The user who accessed the board.', on_delete=django.db.models.deletion.CASCADE, related_name='board_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='author',
            field=models.ForeignKey(help_text='The user who wrote the post.', on_delete=django.db.models.deletion.CASCADE, related_name='project_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='content',
            field=common.fields.EncryptedTextField(help_text='The content of the update (encrypted).'),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='project',
            field=models.ForeignKey(help_text='The project this post belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='project.project'),
        ),
    ]
