# Generated by Django 6.0 on 2026-01-03 08:54

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_projectboardaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=apps.core.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=apps.core.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='content',
            field=apps.core.fields.EncryptedTextField(),
        ),
    ]
