# Generated by Django 6.0 on 2026-01-03 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_alter_message_body_alter_message_subject_and_more'),
        ('project', '0010_alter_project_creation_date_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'recipient', '-timestamp'], name='communicati_sender__7f6e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'sender', '-timestamp'], name='communicati_recipie_3297fc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'is_read', '-timestamp'], name='communicati_recipie_e0bc96_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpost',
            index=models.Index(fields=['project', '-timestamp'], name='communicati_project_159d6d_idx'),
        ),
    ]
