# Generated by Django 6.0 on 2026-01-03 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_alter_message_is_read_alter_message_timestamp_and_more'),
        ('project', '0010_alter_project_creation_date_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projectboardaccess',
            index=models.Index(fields=['project', 'last_accessed'], name='communicati_project_196a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectboardaccess',
            index=models.Index(fields=['user', 'project'], name='communicati_user_id_26d342_idx'),
        ),
    ]
